- apps/backend/api/middleware/validate.ts
- package-lock.json
- package.json
> feat: create default folders

- apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit-general/patient-edit-general.component.html
- apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit-general/patient-edit-general.component.spec.ts
- apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit-general/patient-edit-general.component.ts
- apps/front-end/back-office/src/app/components/quiz-creation/quiz-create/quiz-create.component.spec.ts
- apps/front-end/back-office/src/app/components/util/file-field/file-field.component.ts
> fix: picture preview in patient

- apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit-accommodation/patient-edit-accommodation.component.ts
fix: #186 
The fix may seem incorrect, but it actually makes sense
Why should we refresh the data all the time? The UI already provides feedback. We just need to ensure the data shown is always correct, and that's why we refresh in case of error.
> 186 fix accomodations updates

- apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit-quiz-add-popup/patient-edit-quiz-add-popup.component.html
> fix: add message when no quiz to add

- apps/front-end/back-office/src/app/app.module.ts
- apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-danger/patient-danger.component.html
- apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-danger/patient-danger.component.spec.ts
- apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-danger/patient-danger.component.ts
- apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit/patient-edit.component.html
> feat: add danger zone

- apps/front-end/back-office/project.json
- apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit-stats/patient-edit-stats.component.html
- apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit-stats/patient-edit-stats.component.ts
> feat: more data to charts

- apps/front-end/front-office/src/app/components/drag-and-drop/drag-and-drop.component.html
- apps/front-end/front-office/src/app/components/drag-and-drop/drag-and-drop.component.scss
- apps/front-end/front-office/src/app/components/drag-and-drop/drag-and-drop.component.ts
- apps/front-end/front-office/src/app/components/quiz-view/game-question/game-question.component.scss
- apps/front-end/front-office/src/app/components/quiz-view/help-page/help-page.component.html
- apps/front-end/front-office/src/app/components/quiz-view/help-page/help-page.component.ts
> feat: css shenanigans

- apps/front-end/front-office/src/app/components/quiz-view/help-page/help-page.component.ts
> feat: fuck relative imports

- apps/front-end/front-office/src/app/components/homepage/card-container/card-container.component.html
- apps/front-end/front-office/src/app/components/homepage/card-container/card-container.component.ts
> feat: floor selection

- .husky/pre-commit
- package.json
> feat: add format and validator

- apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-danger/patient-danger.component.html
- apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit-accommodation/patient-edit-accommodation.component.html
- apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit-quiz-add-popup/patient-edit-quiz-add-popup.component.html
- apps/front-end/back-office/src/app/components/dashboard/patient/patient-list/patient-list.component.html
- apps/front-end/back-office/src/app/components/dashboard/quiz/quiz-list/quiz-list.component.html
- libs/data-access-mocks/src/lib/mocks/patient.ts
> fix: grammar issues

- .github/workflows/nx.yml
> ci: add build to ci

- .dockerignore
- apps/backend/api/Dockerfile
- apps/util-scripts/Dockerfile
- prisma/schema.prisma
> fix: docker prisma generate

- apps/backend/api/src/controllers/family-member.controller.ts
- apps/backend/api/src/main.ts
- apps/backend/api/src/routes/family-member.route.ts
> feat: add crud to family-member

- libs/front-end/shared/common/src/lib/services/patient/patient.service.ts
> fix patientservice

- apps/backend/api/src/controllers/clue.controller.ts
- apps/backend/api/src/main.ts
- apps/backend/api/src/routes/clue.route.ts
> feat: clue crud

- apps/front-end/back-office/src/app/components/quiz-edition/quiz-edition.component.ts
- libs/front-end/shared/common/src/lib/services/quiz/quiz.service.ts
> fix quizservice

- apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit-quiz-add-popup/patient-edit-quiz-add-popup.component.html
- apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit-quiz-add-popup/patient-edit-quiz-add-popup.component.ts
- apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit-quiz/patient-edit-quiz.component.html
- apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit-quiz/patient-edit-quiz.component.ts
- apps/front-end/back-office/src/app/components/dashboard/quiz/quiz-list/quiz-list.component.html
- apps/front-end/back-office/src/app/components/dashboard/quiz/quiz-list/quiz-list.component.ts
- apps/front-end/back-office/src/app/components/quiz-creation/question-list/question-list.component.ts
- apps/front-end/back-office/src/app/components/quiz-creation/quiz-create/quiz-create.component.html
- apps/front-end/back-office/src/app/components/quiz-creation/quiz-create/quiz-create.component.ts
- apps/front-end/front-office/src/app/components/quiz-view/game-question/game-question.component.ts
- apps/front-end/front-office/src/app/components/quiz/quiz-item/quiz-item.component.ts
- apps/front-end/front-office/src/app/components/quiz/quiz-list-item/quiz-list-item.component.html
- apps/front-end/front-office/src/app/components/quiz/quiz-list-item/quiz-list-item.component.ts
- apps/util-scripts/src/main.ts
- libs/data-access-mocks/src/lib/mocks/patient.ts
- libs/data-access-mocks/src/lib/mocks/quiz.ts
- prisma/migrations/20230602122322_/migration.sql
- prisma/schema.prisma
> remove stage from quiz creation

- apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit-stats/patient-edit-stats.component.ts
> patient graph title is wrong

- apps/backend/api/src/controllers/patient.accommodation.controller.ts
- apps/backend/api/src/main.ts
- apps/backend/api/src/routes/patient.route.ts
- apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit-accommodation/patient-edit-accommodation.component.ts
- libs/front-end/shared/common/src/lib/services/patient/patient.service.ts
> accommodations cannot be seen / edited

- apps/backend/api/src/main.ts
- apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit-general/patient-edit-general.component.ts
- libs/front-end/shared/common/src/index.ts
- libs/front-end/shared/common/src/lib/utils/fileToBase64.ts
> feat: add util

- libs/front-end/shared/common/src/lib/utils/fileToBase64.ts
> add util to convert img to base64

- apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit-general/patient-edit-general.component.ts
- apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit-quiz/patient-edit-quiz.component.ts
- apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-family/patient-family.component.ts
- apps/front-end/back-office/src/app/components/dashboard/patient/patient-list/patient-list.component.ts
- apps/front-end/back-office/src/app/components/dashboard/quiz/quiz-list/quiz-list.component.ts
- apps/front-end/back-office/src/app/components/quiz-creation/question-edit-general/question-edit-general.component.html
- apps/front-end/back-office/src/app/components/quiz-creation/question-edit-general/question-edit-general.component.ts
- apps/front-end/back-office/src/app/components/util/file-field/file-field.component.ts
- apps/front-end/front-office/src/app/components/quiz/quiz-item/quiz-item.component.ts
- libs/front-end/shared/common/src/index.ts
> fix: quiz edition

- apps/backend/api/package.json
> fix: missing packages

- apps/front-end/back-office/src/app/services/auth/auth.service.ts
- libs/front-end/shared/common/src/lib/services/quiz-session/quiz-session.service.ts
- libs/front-end/shared/common/src/lib/services/quiz/quiz.service.ts
- libs/front-end/shared/common/src/lib/services/tts/tts.service.ts
> fix: missing api routes

- apps/backend/api/src/controllers/patient.question-result.controller.ts
> fix: average

- apps/front-end/back-office/src/app/components/quiz-creation/quiz-create/quiz-create.component.html
- apps/front-end/back-office/src/app/components/quiz-creation/quiz-create/quiz-create.component.ts
- no longer require image
- remove obsolete description field
Ref: #343
> fix: quiz creation

- apps/backend/backend-api-e2e/config/custom-environment-variables.json
- apps/backend/backend-api-e2e/config/default.json
- apps/backend/backend-api-e2e/src/support/test-setup.ts
- apps/front-end/back-office/src/app/components/quiz-creation/question-clue/question-clue.component.ts
- libs/shared/environments/src/lib/environment.ts
> fix: clues
